### 1

В файле /datasets/users_data.csv хранятся данные о действиях пользователя приложения. Прочитайте данные и сохраните в переменной users_data. Приведите столбцы session_start_ts и session_end_ts к типу datetime. Посчитайте метрику MAU за весь период, сохраните результат в переменной mau_total и выведите mau_total.
Обратите внимание, что значение метрики MAU — это целое число.

In [1]:
import pandas as pd

In [2]:
users_data = pd.read_csv('./users_data.csv')
users_data.head()

        session_end_ts     session_start_ts                    id
0  2018-05-12 13:01:00  2018-05-12 12:59:00   6166747268563051447
1  2018-05-12 13:01:00  2018-05-12 13:01:00  14914378861449143644
2  2018-05-12 13:02:00  2018-05-12 13:00:00   3454575477456344412
3  2018-05-12 13:02:00  2018-05-12 13:02:00    630504356053318052
4  2018-05-12 13:03:00  2018-05-12 13:02:00    596727621648472758

In [3]:
users_data['session_start_ts'] = pd.to_datetime(users_data['session_start_ts'])
users_data['session_end_ts'] = pd.to_datetime(users_data['session_end_ts'])

In [9]:
users_data['session_year']  = users_data['session_start_ts'].dt.year
users_data['session_month'] = users_data['session_start_ts'].dt.month
users_data['session_week']  = users_data['session_start_ts'].dt.isocalendar().week 
users_data['session_date'] = users_data['session_start_ts'].dt.date
users_data.head()

,session_end_ts,session_start_ts,id,session_year,session_month,session_date,session_week
0,2018-05-12 13:01:00,2018-05-12 12:59:00,6166747268563051447,2018,5,2018-05-12,19
1,2018-05-12 13:01:00,2018-05-12 13:01:00,14914378861449143644,2018,5,2018-05-12,19
2,2018-05-12 13:02:00,2018-05-12 13:00:00,3454575477456344412,2018,5,2018-05-12,19
3,2018-05-12 13:02:00,2018-05-12 13:02:00,630504356053318052,2018,5,2018-05-12,19
4,2018-05-12 13:03:00,2018-05-12 13:02:00,596727621648472758,2018,5,2018-05-12,19

In [ ]:
dau_total = users_data.groupby('session_date').agg({'id': 'nunique'}).mean()
wau_total = (
    users_data.groupby(['session_year', 'session_week'])
    .agg({'id': 'nunique'})
    .mean()
)

In [12]:
mau_total = (
    users_data.groupby(['session_year','session_month']).agg({'id': 'nunique'}).mean()
)
int(mau_total)

C:\Users\yu.ents\AppData\Local\Temp\ipykernel_15856\18766984.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(mau_total)

25429

### 2

По аналогии с mau_total в прекоде рассчитайте dau_total и wau_total.

Найдите sticky factor по отношению к месячной и недельной аудитории. Сохраните результат для месячной аудитории в переменной sticky_mau, а для недельной — sticky_wau. Умножьте дроби расчёта sticky factor на 100, чтобы получить результат в процентах. Выведите на экран сначала sticky_wau, а затем sticky_mau (без округления и изменения типа данных).

In [14]:
dau_total = users_data.groupby('session_date').agg({'id': 'nunique'}).mean()
int(dau_total)

C:\Users\yu.ents\AppData\Local\Temp\ipykernel_15856\1009230512.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(dau_total)

1536

In [16]:
wau_total = (
    users_data.groupby(['session_year','session_week']).agg({'id': 'nunique'}).mean()
)
int(wau_total)

C:\Users\yu.ents\AppData\Local\Temp\ipykernel_15856\742474642.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  int(wau_total)

8297

In [21]:
sticky_mau = dau_total/mau_total*100
sticky_wau = dau_total/wau_total*100

In [22]:
print(sticky_wau)
print(sticky_mau)

id    18.512582
dtype: float64
id    6.040741
dtype: float64